name        : fontsproto
version     : 2.1.3
release     : 5
source      :
    - http://xorg.freedesktop.org/releases/individual/proto/fontsproto-2.1.3.tar.gz : 72c44e63044b2b66f6fa112921621ecc20c71193982de4f198d9a29cda385c5e
license     :
    - MIT
summary     : X Fonts Extension
component   : xorg.proto
patterns    : /
description : |
    X Fonts Extension
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
